/**
 * Generate a lead detail summary as downloadable HTML (print-to-PDF).
 * Returns HTML string that opens in a new window for print/save as PDF.
 */

type LeadPDFData = {
  name: string;
  phone: string | null;
  email: string | null;
  matterType: string | null;
  status: string;
  score: number | null;
  scoreTier: string | null;
  state: string | null;
  city: string | null;
  summary: string | null;
  injuryStatus: string | null;
  injuryAreas: unknown;
  medicalTreatment: string | null;
  dateRange: string | null;
  notes: string | null;
  createdAt: string;
  assignedTo: string | null;
  aiSummary: string | null;
  aiSeverity: string | null;
};

const MATTER_LABELS: Record<string, string> = {
  car_accident: "Car Accident",
  truck_accident: "Truck Accident",
  motorcycle_accident: "Motorcycle Accident",
  slip_fall: "Slip & Fall",
  wrongful_death: "Wrongful Death",
  other_injury: "Other Injury",
};

export function generateLeadPDFHtml(data: LeadPDFData): string {
  const matter = MATTER_LABELS[data.matterType ?? ""] ?? data.matterType ?? "N/A";
  const location = [data.city, data.state].filter(Boolean).join(", ") || "N/A";
  const areas = Array.isArray(data.injuryAreas) ? data.injuryAreas.join(", ") : String(data.injuryAreas ?? "N/A");

  return `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>Lead Report - ${data.name}</title>
<style>
  body { font-family: -apple-system, sans-serif; max-width: 700px; margin: 0 auto; padding: 40px 20px; color: #0f172a; }
  h1 { font-size: 24px; margin-bottom: 4px; }
  h2 { font-size: 16px; margin-top: 24px; margin-bottom: 8px; border-bottom: 2px solid #e2e8f0; padding-bottom: 4px; }
  .meta { color: #64748b; font-size: 14px; }
  table { width: 100%; border-collapse: collapse; margin-top: 8px; }
  td { padding: 6px 0; font-size: 14px; vertical-align: top; }
  td:first-child { color: #64748b; width: 140px; }
  .badge { display: inline-block; padding: 2px 10px; border-radius: 999px; font-size: 12px; font-weight: 700; }
  .score { background: #dbeafe; color: #2563eb; }
  .status { background: #f1f5f9; color: #334155; }
  .summary { background: #f8fafc; padding: 12px; border-radius: 8px; margin-top: 8px; font-size: 14px; line-height: 1.6; }
  .footer { margin-top: 32px; padding-top: 16px; border-top: 1px solid #e2e8f0; font-size: 12px; color: #94a3b8; }
  @media print { body { padding: 0; } }
</style>
</head>
<body>
<h1>${data.name}</h1>
<p class="meta">${matter} &middot; ${new Date(data.createdAt).toLocaleString()}</p>

<h2>Contact</h2>
<table>
<tr><td>Phone</td><td>${data.phone ?? "N/A"}</td></tr>
<tr><td>Email</td><td>${data.email ?? "N/A"}</td></tr>
<tr><td>Assigned To</td><td>${data.assignedTo ?? "Unassigned"}</td></tr>
<tr><td>Status</td><td><span class="badge status">${data.status}</span></td></tr>
<tr><td>Score</td><td>${data.score != null ? `<span class="badge score">${data.score} (${data.scoreTier})</span>` : "N/A"}</td></tr>
</table>

<h2>Case Details</h2>
<table>
<tr><td>Matter Type</td><td>${matter}</td></tr>
<tr><td>Location</td><td>${location}</td></tr>
<tr><td>When</td><td>${data.dateRange ?? "N/A"}</td></tr>
<tr><td>Injury Status</td><td>${data.injuryStatus ?? "N/A"}</td></tr>
<tr><td>Injury Areas</td><td>${areas}</td></tr>
<tr><td>Treatment</td><td>${data.medicalTreatment ?? "N/A"}</td></tr>
</table>

${data.summary ? `<h2>Incident Summary</h2><div class="summary">${data.summary}</div>` : ""}
${data.aiSummary ? `<h2>AI Analysis</h2><table><tr><td>Severity</td><td>${data.aiSeverity ?? "N/A"}</td></tr><tr><td>Summary</td><td>${data.aiSummary}</td></tr></table>` : ""}
${data.notes ? `<h2>Additional Notes</h2><div class="summary">${data.notes}</div>` : ""}

<div class="footer">Generated by IntakeLLG &middot; ${new Date().toLocaleString()}</div>
<script>window.print();</script>
</body></html>`;
}
